baseURL: https://samircaus.github.io/
languageCode: en-us
title: Scaus Art

# disable taxonomy pages
taxonomies: []

permalinks:
  posts: /:year/:month/:title/

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9
  highlight:
    style: friendly

menu:
  main:
  # individual pages are added to menu in their front matter
  - identifier: blog
    name: Blog
    url: https://scaus.art/blog
    rel: noopener
    weight: 10
  - identifier: github
    name: GitHub
    url: https://github.com/samircaus
    weight: 20
